AVERAGE_CARD_CREATE_TIME = 75
CARD_CREATE_TIME_SCALE = 10

MAX_TIME_OPERATOR_RECALL_WAITING = 10
AVG_TIME_OPERATOR_RECALL_WAITING = 5
OPERATOR_RECALL_WAITING_SCALE = 2

MAX_TIME_OPERATOR_WAITING = 60
AVG_TIME_OPERATOR_WAITING = 15
OPERATOR_TIME_WAITING_SCALE = 10

OPERATOR_REACTION_TIME = 8
OPERATOR_REACTION_TIME_SCALE = 3
