AVERAGE_CARD_CREATE_TIME = 75
CARD_CREATE_TIME_SCALE = 10

MAX_TIME_OPERATOR_RECALL_WAITING = 10
AVG_TIME_OPERATOR_RECALL_WAITING = 5
OPERATOR_RECALL_WAITING_SCALE = 2

MAX_TIME_OPERATOR_WAITING = 60
AVG_TIME_OPERATOR_WAITING = 15
OPERATOR_TIME_WAITING_SCALE = 10
OPERATOR_REACTION_TIME = 8
OPERATOR_REACTION_TIME_SCALE = 3

# in %
EOS_SHARE_MIN = 55
EOS_SHARE_MAX = 65

# main eos in %
FIRE_SHARE_MIN = 2
FIRE_SHARE_MAX = 10

POLICE_SHARE_MIN = 15
POLICE_SHARE_MAX = 25

AMBULANCE_SHARE_MIN = 55
AMBULANCE_SHARE_MAX = 70

GAS_SHARE_MIN = 0
GAS_SHARE_MAX = 10

CARD_CS_SHARE_MIN = 0
CARD_CS_SHARE_MAX = 5

CARD_AT_SHARE_MIN = 0
CARD_AT_SHARE_MAX = 2
# other eos in %
MCHS_SHARE_MIN = 0
MCHS_SHARE_MAX = 1

EDDS_SHARE_MIN = 0
EDDS_SHARE_MAX = 1

ROSGV_SHARE_MIN = 0
ROSGV_SHARE_MAX = 1

AVIALES_SHARE_MIN = 0
AVIALES_SHARE_MAX = 1

ROSAVTODOR_SHARE_MIN = 0
ROSAVTODOR_SHARE_MAX = 1

ROSLESHOZ_SHARE_MIN = 0
ROSLESHOZ_SHARE_MAX = 1
