s = {1: {'count': 10,
         'var': [{'name': 'Авария ЖКХ в доме (электрика, вода, канализация, '
                          'теплосеть)',
                  'section_max': 3,
                  'section_min': 1},
                 {'name': 'Аварийно - спасательные работы',
                  'section_max': 7,
                  'section_min': 4},
                 {'name': 'Возгорание на линии',
                  'section_max': 10,
                  'section_min': 8}]},
     2: {'count': 8,
         'var': [{'name': 'Вскрытие автомобиль',
                  'section_max': 5,
                  'section_min': 1},
                 {'name': 'Угроза убийством', 'section_max': 8, 'section_min': 6}]},
     3: {'count': 29,
         'var': [{'name': 'Боли в животе', 'section_max': 15, 'section_min': 1},
                 {'name': 'Боли в пояснице', 'section_max': 26, 'section_min': 16},
                 {'name': 'Возгорание на линии',
                  'section_max': 29,
                  'section_min': 27}]},
     4: {'count': 4,
         'var': [{'name': 'Газ. Запах газа в помещении.',
                  'section_max': 4,
                  'section_min': 1}]},
     5: {'count': 3,
         'var': [{'name': 'Угроза убийством', 'section_max': 3, 'section_min': 1}]},
     6: {'count': 12,
         'var': [{'name': 'Авария ЖКХ в доме (электрика, вода, канализация, '
                          'теплосеть)',
                  'section_max': 3,
                  'section_min': 1},
                 {'name': 'ЖКХ', 'section_max': 12, 'section_min': 4}]}}
